version: '3.8'

services:
  bot:
    build: .
    container_name: leech_bot
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      - QB_HOST=localhost
      - QB_PORT=8090
    volumes:
      - ./downloads:/app/downloads
      - ./settings.json:/app/settings.json
    ports:
      - "8090:8090" # Expose WebUI if needed (Tailscale)
